version: '3.8'

services:
  gcs-emulator:
    build: .
    image: fsouza/fake-gcs-server
    container_name: fake-gcs-server
    ports:
      - "4443:4443"
    volumes:
      - ./gcs-data:/data
    command: -scheme http

  postgres:
    image: postgres:13
    container_name: postgres-test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
